import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { flex } from "@/styled-system/patterns";
import { css, cx } from "@/styled-system/css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cx(
          inter.className,
          css({
            display: "grid",
            gridTemplateRows: "auto 1fr auto",
            minHeight: "100vh",
          })
        )}
      >
        <header
          className={flex({
            justify: "center",
          })}
        >
          Header
        </header>
        <div>{children}</div>
        <footer
          className={flex({
            width: "100%",
            justify: "center",
            background: "var(--background-secondary)",
          })}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
