import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cx } from "@/styled-system/css";
import { flex } from "@/styled-system/patterns";
import { MainNavigation } from "@/components/MainNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cx(
          inter.className,
          flex({
            direction: "column",
            minHeight: "100vh",
            minWidth: "100vw",
          })
        )}
      >
        <header
          className={flex({
            height: "3rem",
            minHeight: "3rem",
            maxHeight: "3rem",
            width: "100%",
            justify: "center",
          })}
        >
          Header
        </header>
        <div
          className={flex({
            flex: "1 1 auto",
          })}
        >
          <div
            className={flex({
              width: "20rem",
              minWidth: "20rem",
              maxWidth: "20rem",
              overflow: "auto",
            })}
          >
            <MainNavigation />
          </div>
          <main
            className={flex({
              flex: "1 1 auto",
            })}
          >
            {children}
          </main>
        </div>
        <footer
          className={flex({
            height: "1.5rem",
            minHeight: "1.5rem",
            maxHeight: "1.5rem",
            width: "100%",
            justify: "center",
            background: "var(--background-secondary)",
          })}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
